# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.loadVideoWidget = QtWidgets.QWidget(MainWindow)
        self.loadVideoWidget.setObjectName("loadVideoWidget")
        self.loadVidBtn = QtWidgets.QPushButton(self.loadVideoWidget)
        self.loadVidBtn.setGeometry(QtCore.QRect(140, 260, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadVidBtn.setFont(font)
        self.loadVidBtn.setObjectName("loadVidBtn")
        self.noteLabel = QtWidgets.QLabel(self.loadVideoWidget)
        self.noteLabel.setGeometry(QtCore.QRect(300, 310, 211, 16))
        self.noteLabel.setObjectName("noteLabel")
        MainWindow.setCentralWidget(self.loadVideoWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrum Analyzer Tool: Video Processor"))
        self.loadVidBtn.setText(_translate("MainWindow", "Press to Select Video File"))
        self.noteLabel.setText(_translate("MainWindow", "Note: File Type Must Be mp4 or mkv"))
